name: 'My Composite Action'
description: 'This action runs a sequence of steps'

inputs:
  username:
    description: 'The name of the user'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print greeting
      run: |
        echo "Hello"
      shell: bash  # Specify the shell to use for running the script
