name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to pass to the workflow'
        required: false
        type: string
      message:
        description: 'Custom message for the greeting'
        required: false
        type: string
        
  workflow_call:
    inputs:
      username:
        description: 'Username to pass to child workflow'
        required: true
        type: string
      message:
        description: 'Custom message for the greeting'
        required: true
        type: string

jobs:
  Python-Syntax-Check:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to access the 'actions' directory

      - name: Print message 
        uses: ./actions

      
      #- name: Checkout code
      #  uses: actions/checkout@v2
        
      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #     python-version: 3.x
      
      #- name: Check syntax of Python files
      #  run: python -m compileall .
